// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OfficeChecker.Data;

namespace OfficeChecker.Migrations
{
    [DbContext(typeof(OfficeContext))]
    [Migration("20210119161428_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("OfficeChecker.Models.Office", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdditionalInfo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<string>("DressCode")
                        .HasColumnType("TEXT");

                    b.Property<int>("FaceCoverings")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LocationType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MarketUnit")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OfficeName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<int>("OfficeServices")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OfficeStatus")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("OtherProtocols")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhysicalDistancing")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ReservableSpace")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SpecialDetails")
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TechSupport")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TemperatureChecking")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("TemperatureChecks")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Visitors")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Zip")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Office");
                });
#pragma warning restore 612, 618
        }
    }
}
